/** Nederlandse namen voor landen en groepen */

export const DUTCH_TEAM_NAMES: Record<string, string> = {
  // Europa
  "Germany": "Duitsland",
  "France": "Frankrijk",
  "Spain": "Spanje",
  "Netherlands": "Nederland",
  "England": "Engeland",
  "Portugal": "Portugal",
  "Belgium": "België",
  "Italy": "Italië",
  "Croatia": "Kroatië",
  "Serbia": "Servië",
  "Poland": "Polen",
  "Sweden": "Zweden",
  "Denmark": "Denemarken",
  "Norway": "Noorwegen",
  "Switzerland": "Zwitserland",
  "Austria": "Oostenrijk",
  "Hungary": "Hongarije",
  "Czech Republic": "Tsjechië",
  "Czechia": "Tsjechië",
  "Slovakia": "Slowakije",
  "Slovenia": "Slovenië",
  "Romania": "Roemenië",
  "Bulgaria": "Bulgarije",
  "Greece": "Griekenland",
  "Turkey": "Turkije",
  "Ukraine": "Oekraïne",
  "Scotland": "Schotland",
  "Wales": "Wales",
  "Northern Ireland": "Noord-Ierland",
  "Republic of Ireland": "Ierland",
  "Ireland": "Ierland",
  "Finland": "Finland",
  "Iceland": "IJsland",
  "Albania": "Albanië",
  "Kosovo": "Kosovo",
  "Georgia": "Georgië",
  "North Macedonia": "Noord-Macedonië",
  "Bosnia and Herzegovina": "Bosnië-Herzegovina",
  "Bosnia-Herzegovina": "Bosnië-Herzegovina",
  "Montenegro": "Montenegro",
  "Luxembourg": "Luxemburg",
  "Estonia": "Estland",
  "Latvia": "Letland",
  "Lithuania": "Litouwen",
  "Moldova": "Moldavië",
  "Armenia": "Armenië",
  "Azerbaijan": "Azerbeidzjan",
  "Kazakhstan": "Kazachstan",
  "Cyprus": "Cyprus",
  "Malta": "Malta",
  "Andorra": "Andorra",
  "Faroe Islands": "Faeröer",
  // Noord/Midden-Amerika & Caraïben
  "United States": "Verenigde Staten",
  "USA": "VS",
  "Canada": "Canada",
  "Mexico": "Mexico",
  "Costa Rica": "Costa Rica",
  "Panama": "Panama",
  "Honduras": "Honduras",
  "Guatemala": "Guatemala",
  "El Salvador": "El Salvador",
  "Jamaica": "Jamaica",
  "Trinidad and Tobago": "Trinidad en Tobago",
  "Haiti": "Haïti",
  "Cuba": "Cuba",
  "Curaçao": "Curaçao",
  // Zuid-Amerika
  "Brazil": "Brazilië",
  "Argentina": "Argentinië",
  "Colombia": "Colombia",
  "Uruguay": "Uruguay",
  "Chile": "Chili",
  "Ecuador": "Ecuador",
  "Peru": "Peru",
  "Bolivia": "Bolivia",
  "Paraguay": "Paraguay",
  "Venezuela": "Venezuela",
  // Afrika
  "Morocco": "Marokko",
  "Senegal": "Senegal",
  "Nigeria": "Nigeria",
  "Cameroon": "Kameroen",
  "Ghana": "Ghana",
  "Egypt": "Egypte",
  "South Africa": "Zuid-Afrika",
  "Algeria": "Algerije",
  "Tunisia": "Tunesië",
  "Ivory Coast": "Ivoorkust",
  "Côte d'Ivoire": "Ivoorkust",
  "Mali": "Mali",
  "Mozambique": "Mozambique",
  "Angola": "Angola",
  "Zambia": "Zambia",
  "Zimbabwe": "Zimbabwe",
  "Tanzania": "Tanzania",
  "Kenya": "Kenia",
  "Uganda": "Oeganda",
  "Rwanda": "Rwanda",
  "DR Congo": "DR Congo",
  "Benin": "Benin",
  "Cape Verde": "Kaapverdië",
  "Guinea": "Guinee",
  "Sierra Leone": "Sierra Leone",
  "Ethiopia": "Ethiopië",
  "Gabon": "Gabon",
  "Mauritius": "Mauritius",
  "Mauritania": "Mauretanië",
  "Namibia": "Namibië",
  "Sudan": "Soedan",
  "Libya": "Libië",
  "Togo": "Togo",
  "Burkina Faso": "Burkina Faso",
  "Congo": "Congo",
  "Madagascar": "Madagaskar",
  "Comoros": "Comoren",
  "Gambia": "Gambia",
  // Azië & Oceanië
  "Japan": "Japan",
  "South Korea": "Zuid-Korea",
  "Korea Republic": "Zuid-Korea",
  "Australia": "Australië",
  "Iran": "Iran",
  "Saudi Arabia": "Saudi-Arabië",
  "Qatar": "Qatar",
  "Iraq": "Irak",
  "Jordan": "Jordanië",
  "United Arab Emirates": "VAE",
  "UAE": "VAE",
  "China": "China",
  "China PR": "China",
  "India": "India",
  "Indonesia": "Indonesië",
  "Vietnam": "Vietnam",
  "Thailand": "Thailand",
  "Philippines": "Filipijnen",
  "Oman": "Oman",
  "Kuwait": "Koeweit",
  "Bahrain": "Bahrein",
  "Lebanon": "Libanon",
  "Syria": "Syrië",
  "Uzbekistan": "Oezbekistan",
  "Afghanistan": "Afghanistan",
  "New Zealand": "Nieuw-Zeeland",
  "Fiji": "Fiji",
  "Papua New Guinea": "Papoea-Nieuw-Guinea",
  "Solomon Islands": "Salomoneilanden",
  "Vanuatu": "Vanuatu",
}

/** Geef de Nederlandse naam, anders de originele naam terug */
export function getDutchName(name: string): string {
  return DUTCH_TEAM_NAMES[name] ?? name
}

/** Vertaal "GROUP_A" naar "Groep A", "GROUP_B" naar "Groep B", etc. */
export function formatGroupName(groupName: string | null | undefined): string {
  if (!groupName) return ""
  return groupName
    .replace(/^GROUP_/, "Groep ")
    .replace(/^LEAGUE_/, "")
    .replace(/_/g, " ")
}
